### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by chrisnatali** [Banrai/TeamWork.io#1]
Maybe wiki entries for suggested use cases (user -> user, user -> group messages) and concepts (not clear what a session is to me)?

**Comment by dpapathanasiou** [comment]
A "session" is just a password-less login: instead of relying on something that can be stolen or forgotten, you have to prove you can decrypt a random passphrase which was encrypted with your public key

I've updated the help to explain that better:

https://teamwork.io/help.html#decrypt-session

And I've also made it more obvious when prompted to create one: https://github.com/Banrai/TeamWork.io/commit/fcc3e0dfa2c12aa5ebf6a3e2b55f07ebb539dadf
